#!/bin/sh
rm *.aux 2> /dev/null
rm *.toc 2> /dev/null
rm *.out 2> /dev/null
rm *.bak 2> /dev/null
rm *.brf 2> /dev/null
rm *.blg 2> /dev/null
rm *.bbl 2> /dev/null
rm *.lof 2> /dev/null
rm *.lot 2> /dev/null
rm *.lol 2> /dev/null
rm *.dvi 2> /dev/null
rm *.idx 2> /dev/null
rm *.ind 2> /dev/null
rm *.glo 2> /dev/null
rm *.gls 2> /dev/null
rm *.nlo 2> /dev/null
rm *.log 2> /dev/null
rm *.backup 2> /dev/null
